# Generated by Django 3.1.4 on 2021-02-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('querry', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
