# Generated by Django 3.1.4 on 2021-02-13 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210211_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='querry',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
