# Generated by Django 3.1.4 on 2021-02-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210213_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
