# Generated by Django 3.1.4 on 2021-02-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_studentmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
