# Generated by Django 3.1.4 on 2021-02-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_studentmodel_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='body',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='picture',
        ),
    ]
